import { useCallback, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface ExportOptions {
  filename?: string;
  title?: string;
  subtitle?: string;
}

export function usePdfExport() {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPdf = useCallback(async (
    elementId: string,
    options: ExportOptions = {}
  ) => {
    const { 
      filename = "herd-projection-report.pdf",
      title = "Herd Projection Report",
      subtitle = "Generated by FHPS"
    } = options;

    setIsExporting(true);

    try {
      const element = document.getElementById(elementId);
      if (!element) {
        throw new Error("Element not found");
      }

      // Temporarily expand all scroll containers for full capture
      const scrollContainers = element.querySelectorAll<HTMLElement>('[class*="max-h-"], [class*="overflow"]');
      const origStyles: { el: HTMLElement; maxHeight: string; overflow: string; overflowY: string }[] = [];
      
      // Force light theme for PDF capture on both html and body
      const htmlEl = document.documentElement;
      const bodyEl = document.body;
      const wasDark = htmlEl.classList.contains("dark");
      if (wasDark) {
        htmlEl.classList.remove("dark");
        bodyEl.classList.remove("dark");
        htmlEl.classList.add("light");
        bodyEl.classList.add("light");
      }

      // Save and override the main element
      origStyles.push({ el: element, maxHeight: element.style.maxHeight, overflow: element.style.overflow, overflowY: element.style.overflowY });
      element.style.maxHeight = "none";
      element.style.overflow = "visible";
      element.style.overflowY = "visible";
      
      // Save and override all nested scroll containers
      scrollContainers.forEach(el => {
        origStyles.push({ el, maxHeight: el.style.maxHeight, overflow: el.style.overflow, overflowY: el.style.overflowY });
        el.style.maxHeight = "none";
        el.style.overflow = "visible";
        el.style.overflowY = "visible";
      });

      // Force all SVG text/ticks in charts to be dark for readability
      const svgTexts = element.querySelectorAll<SVGElement>("svg text, svg .recharts-cartesian-axis-tick-value, svg .recharts-legend-item-text, svg .recharts-label");
      const svgOriginals: { el: SVGElement; fill: string }[] = [];
      svgTexts.forEach(el => {
        svgOriginals.push({ el, fill: el.getAttribute("fill") || "" });
        el.setAttribute("fill", "#1a1a1a");
      });

      // Force axis lines to be visible
      const svgLines = element.querySelectorAll<SVGElement>("svg .recharts-cartesian-axis-line, svg .recharts-cartesian-grid-horizontal line, svg .recharts-cartesian-grid-vertical line");
      const lineOriginals: { el: SVGElement; stroke: string }[] = [];
      svgLines.forEach(el => {
        lineOriginals.push({ el, stroke: el.getAttribute("stroke") || "" });
        el.setAttribute("stroke", "#cccccc");
      });

      // Brief delay for theme repaint
      await new Promise(r => setTimeout(r, 200));

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#faf8f5",
        windowWidth: 1200,
      });

      // Restore all original styles
      origStyles.forEach(({ el, maxHeight, overflow, overflowY }) => {
        el.style.maxHeight = maxHeight;
        el.style.overflow = overflow;
        el.style.overflowY = overflowY;
      });

      // Restore SVG text fills
      svgOriginals.forEach(({ el, fill }) => {
        if (fill) el.setAttribute("fill", fill);
        else el.removeAttribute("fill");
      });
      lineOriginals.forEach(({ el, stroke }) => {
        if (stroke) el.setAttribute("stroke", stroke);
        else el.removeAttribute("stroke");
      });

      // Restore dark theme if it was active
      if (wasDark) {
        htmlEl.classList.remove("light");
        bodyEl.classList.remove("light");
        htmlEl.classList.add("dark");
        bodyEl.classList.add("dark");
      }

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - (margin * 2);

      // ─── Header ───
      pdf.setFillColor(59, 102, 67);
      pdf.rect(0, 0, pageWidth, 38, "F");
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(24);
      pdf.setFont("helvetica", "bold");
      pdf.text(title, margin, 18);
      
      pdf.setFontSize(10);
      pdf.setFont("helvetica", "normal");
      pdf.text(subtitle, margin, 28);
      
      const dateStr = new Date().toLocaleDateString("en-US", { 
        year: "numeric", month: "long", day: "numeric" 
      });
      pdf.text(`Generated: ${dateStr}`, pageWidth - margin, 28, { align: "right" });

      // Thin accent bar under header
      pdf.setFillColor(200, 180, 120);
      pdf.rect(0, 38, pageWidth, 1.5, "F");

      // ─── Content ───
      const imgWidth = contentWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      const startY = 48;

      let remainingHeight = imgHeight;
      let currentY = startY;
      let sourceY = 0;
      let pageNum = 1;

      while (remainingHeight > 0) {
        const footerSpace = 16;
        const availableHeight = pageHeight - currentY - footerSpace;
        const drawHeight = Math.min(remainingHeight, availableHeight);
        const sourceHeight = (drawHeight / imgHeight) * canvas.height;

        const croppedCanvas = document.createElement("canvas");
        croppedCanvas.width = canvas.width;
        croppedCanvas.height = sourceHeight;
        const ctx = croppedCanvas.getContext("2d");
        
        if (ctx) {
          ctx.drawImage(
            canvas,
            0, sourceY,
            canvas.width, sourceHeight,
            0, 0,
            canvas.width, sourceHeight
          );
          
          const croppedImgData = croppedCanvas.toDataURL("image/png");
          pdf.addImage(croppedImgData, "PNG", margin, currentY, imgWidth, drawHeight);
        }

        // ─── Footer on every page ───
        pdf.setDrawColor(200, 200, 200);
        pdf.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);
        
        pdf.setTextColor(140, 140, 140);
        pdf.setFontSize(8);
        pdf.text(
          "FHPS • Fibonacci-Based Herd Projection System",
          margin,
          pageHeight - 8
        );
        pdf.text(
          `Page ${pageNum}`,
          pageWidth - margin,
          pageHeight - 8,
          { align: "right" }
        );

        remainingHeight -= drawHeight;
        sourceY += sourceHeight;

        if (remainingHeight > 0) {
          pdf.addPage();
          pageNum++;
          currentY = margin;
        }
      }

      pdf.save(filename);
    } catch (error) {
      console.error("PDF export failed:", error);
      throw error;
    } finally {
      setIsExporting(false);
    }
  }, []);

  return { exportToPdf, isExporting };
}